In [9]:
YEAR='2019'
RES_PATH='C:\\Users\\14106\\GAT\\result\\'
PRO_PATH='C:\\Users\\14106\\GAT\\preprocessed'+YEAR+'\\'
CODE_PATH="C:\\Users\\14106\\GAT\\"
RAW_PATH="C:\\Users\\14106\\GAT\\100school\\"

#C:\Backup of covid project\2cls_CScombined_negVSnonneg
import numpy as np 
import urllib.request 
import os 
import csv 
import requests 
import time
import math
import rando
import pandas as pd
from collections import defaultdict
import pickle
import heapq
import pickle
import warnings
import tqdm
#from keras.preprocessing.sequence import pad_sequences
from math import exp
import random
from collections import defaultdict

ORIG_UNIV=['columbia',"notredame","uofm","UCSD",'berkeley',"Harvard","ucla", 'dartmouth']
REGION={'WEST':['AK','HI','WA','OR','CA','MT','ID','WY',
                'NV','UT','CO','AZ','NM'],
        'MIDWEST':['ND','SD','NE','KS','MN','IA',
                  'MO','WI','IL','IN','MI','OH'],
        'NORTHEAST':['NY','NJ','PA','ME','VT','NH','MA','CT','RI'],
        'SOUTH':['OK','TX','AR','LA','KY','TN','MS','AL',
                'WV','DE','MD','DC','VA','NC','SC','GA','FL']}

STATE2REG=dict()
for key, val in REGION.items():
    for s in val:
        STATE2REG[s]=key
            
def get_region(s:str):
    return STATE2REG[s]
    
def categorize_rank(rank):
    if np.isnan(rank):
        return '6'
    if rank<=20:
        return '1'
    elif rank<=50:
        return '2'
    elif rank<=100:
        return '3'
    elif rank<200:
        return '4'
    elif rank<500:
        return '5'
    else:
        return '6'
os.chdir(RAW_PATH)
dat = pd.read_csv('colleges-CCIHE-final.csv')

In [2]:
random.seed(1)
dat['region']=dat['stabbr'].apply(get_region)
dat['rank']=dat['rankings'].apply(categorize_rank)
#dat=dat.sample(frac=1)#[]
schools=list(dat.subreddit)
df=dat.loc[:,['rank','D1','sector','region']]
X=pd.get_dummies(df, columns = ['rank','D1','sector','region']).values

In [3]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
cluster=kmeans.labels_

In [10]:
cat=defaultdict()
for i,val in enumerate(schools):

In [107]:
for s in ORIG_UNIV:
    print(cluster[list(schools).index(s)])

1
1
0
0
0
1
0
1


# Use Euclidian distance to classify

In [4]:
centroids=[]
for s in ORIG_UNIV:
    centroids.append(X[list(schools).index(s),:])
    
dis=[]
for i in range(len(X)):
    cur=X[i,:]
    d=[]
    for c in centroids:
        d.append(sum(cur!=c))
    dis.append(d)
        

In [5]:
dic=defaultdict(list)
for i, val in enumerate(dis):
    m=min(val)
    s=schools[i]
    for j,v in enumerate(val):
        if v==m:
            dic[s].append(ORIG_UNIV[j])

for u in ORIG_UNIV:
    dic[u]=[u]

In [6]:
import pickle 
os.chdir(CODE_PATH)
with open('cluster.pkl', 'wb') as f:
    pickle.dump(dic, f)
        
with open('cluster.pkl', 'rb') as f:
    loaded_dict = pickle.load(f)

In [7]:
dis[list(schools).index('columbia')]

[0, 2, 6, 6, 4, 0, 4, 0]

In [8]:
dic['columbia']

['columbia']

In [69]:
centroids

[array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], dtype=uint8),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=uint8)]

# Dafrt below

In [63]:
school8 = ["notredame","uofm","UCSD",'berkeley',"Harvard","ucla", 'dartmouth','columbia']
for s in school8:
    print(dic[s])

['notredame']
['berkeley', 'ucla']
['columbia', 'notredame', 'uofm', 'UCSD', 'Harvard', 'dartmouth']
['columbia', 'notredame', 'Harvard', 'dartmouth']
['columbia', 'uofm', 'UCSD', 'berkeley', 'Harvard', 'ucla', 'dartmouth']
['uofm', 'UCSD', 'berkeley', 'ucla']
['UCSD', 'berkeley', 'ucla']
['columbia', 'uofm', 'UCSD', 'berkeley', 'Harvard', 'ucla', 'dartmouth']


In [37]:
os.chdir('C:\\Users\\14106\\GAT\\result\\')
#ORIG_UNIV=['columbia',"notredame","uofm","UCSD",'berkeley',"Harvard","ucla", 'dartmouth']`
s=ORIG_UNIV[0]
name=s+'_'+YEAR+'.p'
predicted1=pickle.load(open(name,'rb'))
print(predicted1[0:20])
len(predicted1)

[[-0.54500896  0.600409  ]
 [-0.76511043  0.8479979 ]
 [ 0.20801222 -0.26448786]
 [-0.2021043   0.20153818]
 [ 0.5053316  -0.5980596 ]
 [ 0.3628386  -0.4315721 ]
 [-0.84562033  0.9378486 ]
 [-0.95882386  1.0827218 ]
 [ 0.7234084  -0.83804345]
 [-1.2614318   1.4030232 ]
 [ 0.35727158 -0.43184406]
 [-1.7094467   1.9438758 ]
 [-0.98619944  1.098062  ]
 [ 0.10847789 -0.1426439 ]
 [-0.3289137   0.3441916 ]
 [-0.70975417  0.78641397]
 [ 0.61345935 -0.7148829 ]
 [ 0.3209633  -0.38510382]
 [-0.28724432  0.28969663]
 [-0.42340645  0.4478697 ]]


5031

In [38]:
os.chdir('C:\\Users\\14106\\Downloads\\re1\\')
name=s+YEAR+'.p'
predicted=pickle.load(open(name,'rb'))
print(predicted[0:20])
len(predicted)

[[ 0.54355323 -0.6392615 ]
 [ 0.23279878 -0.28592438]
 [ 0.20801216 -0.2644878 ]
 [ 0.08501468 -0.11840931]
 [ 0.5053315  -0.5980595 ]
 [ 0.3628384  -0.43157184]
 [-0.8456204   0.93784875]
 [-0.5148354   0.56726605]
 [ 0.7234084  -0.8380435 ]
 [-0.59387773  0.6364555 ]
 [ 0.3572716  -0.4318441 ]
 [-1.4676734   1.6690197 ]
 [-0.9861995   1.098062  ]
 [ 0.10847782 -0.14264384]
 [-0.3289137   0.3441916 ]
 [-0.70975417  0.786414  ]
 [ 0.52097994 -0.6102656 ]
 [ 0.64672726 -0.7614497 ]
 [-0.61289704  0.65939826]
 [-1.6616393   1.8596547 ]]


5031

In [39]:
print(predicted[0:20]-predicted1[0:20])


[[ 1.0885623e+00 -1.2396705e+00]
 [ 9.9790919e-01 -1.1339223e+00]
 [-5.9604645e-08  5.9604645e-08]
 [ 2.8711897e-01 -3.1994748e-01]
 [-5.9604645e-08  1.1920929e-07]
 [-2.0861626e-07  2.6822090e-07]
 [-5.9604645e-08  1.1920929e-07]
 [ 4.4398844e-01 -5.1545578e-01]
 [ 0.0000000e+00 -5.9604645e-08]
 [ 6.6755408e-01 -7.6656777e-01]
 [ 2.9802322e-08 -2.9802322e-08]
 [ 2.4177325e-01 -2.7485609e-01]
 [-5.9604645e-08  0.0000000e+00]
 [-7.4505806e-08  5.9604645e-08]
 [ 0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  5.9604645e-08]
 [-9.2479408e-02  1.0461730e-01]
 [ 3.2576397e-01 -3.7634587e-01]
 [-3.2565272e-01  3.6970162e-01]
 [-1.2382329e+00  1.4117850e+00]]
